{
  "formatVersion": "1.1",
  "component": {
    "group": "net.faketuna",
    "module": "kerfb",
    "version": "0.0.2c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.7.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kerfb-0.0.2c.jar",
          "url": "kerfb-0.0.2c.jar",
          "size": 24812,
          "sha512": "3dac57b4862266592873e5022c80e870482e1f4ae05a2fefb479e367bc935657ed1c9a5129ba01667ac6380f285c056f71c2d05b29095e9dea56165cdd54518f",
          "sha256": "fdee7b16034105b56dddf59269ebfb88f12b63da4796557d2255c8b73d3d35d2",
          "sha1": "df6aec5470e59d3dbb0db7b3159e22ab243dba32",
          "md5": "9f0b937eb5277675cd9221481f16fe68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.7.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kerfb-0.0.2c.jar",
          "url": "kerfb-0.0.2c.jar",
          "size": 24812,
          "sha512": "3dac57b4862266592873e5022c80e870482e1f4ae05a2fefb479e367bc935657ed1c9a5129ba01667ac6380f285c056f71c2d05b29095e9dea56165cdd54518f",
          "sha256": "fdee7b16034105b56dddf59269ebfb88f12b63da4796557d2255c8b73d3d35d2",
          "sha1": "df6aec5470e59d3dbb0db7b3159e22ab243dba32",
          "md5": "9f0b937eb5277675cd9221481f16fe68"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kerfb-0.0.2c-universal.jar",
          "url": "kerfb-0.0.2c-universal.jar",
          "size": 4921552,
          "sha512": "2915b9513fd3beea9eb63a7e69a66414405b479ac0926dd9dc50059ac4c6af23704737d253e9da64abdf7cb39405bb4f37c88a58c0342ee58252d15fde383e06",
          "sha256": "02b119e82c59fe3dea46bcd86b3bec6ed5f447067b13e380e1e1d70eaacd47bb",
          "sha1": "63403b2d08c96fef7497956a69a0fb3e7b59d0f2",
          "md5": "7957342373486754f4c88119cb083d15"
        }
      ]
    }
  ]
}
