{
  "formatVersion": "1.1",
  "component": {
    "group": "net.faketuna",
    "module": "kerfb",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kerfb-0.0.1.jar",
          "url": "kerfb-0.0.1.jar",
          "size": 14113,
          "sha512": "019af04db8ed49a8ede313834731b0bb2557df492b27050b225a47ab7d8228d7ee67aae3eb47c429ca734522036a66c324c6db9d687047af3cfabaf7756753f0",
          "sha256": "f16b1419a84029a0d8b6df1ea7a6064abc884286041bb71fb4b103434aba88a6",
          "sha1": "941e0b044957a2bf36747a21de3de1aa7c08b81c",
          "md5": "77bcd8715a8044409cb9cc9448c74336"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.7.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kerfb-0.0.1.jar",
          "url": "kerfb-0.0.1.jar",
          "size": 14113,
          "sha512": "019af04db8ed49a8ede313834731b0bb2557df492b27050b225a47ab7d8228d7ee67aae3eb47c429ca734522036a66c324c6db9d687047af3cfabaf7756753f0",
          "sha256": "f16b1419a84029a0d8b6df1ea7a6064abc884286041bb71fb4b103434aba88a6",
          "sha1": "941e0b044957a2bf36747a21de3de1aa7c08b81c",
          "md5": "77bcd8715a8044409cb9cc9448c74336"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kerfb-0.0.1-universal.jar",
          "url": "kerfb-0.0.1-universal.jar",
          "size": 4910853,
          "sha512": "030e433890974dde63abc472730cf3be205c74c2beb3e8ddaab5e65167531e6868f99242eca12ec41f2de31d697df2ef1494c8fd752323c21e59ae585dbd1d76",
          "sha256": "076d17e640bcff6e74f41a597bafd6a81fe09c9c1b1f81b41680d148c38fdf53",
          "sha1": "53fa55095277470fe468084efc89f3ba66316c8b",
          "md5": "d14555f0d96a5f29ef2d53bb67c7aae1"
        }
      ]
    }
  ]
}
